"""Export functions for interoperability with other tools."""

import numpy as np
import pandas as pd
from typing import Optional, List, Dict, Any
import os
import json


def to_seurat(
    X: np.ndarray,
    labels: np.ndarray,
    embeddings: np.ndarray,
    confidence: Optional[np.ndarray] = None,
    gene_names: Optional[List[str]] = None,
    cell_names: Optional[List[str]] = None,
    output_dir: str = "seurat_export",
    project_name: str = "scGCL"
) -> str:
    """
    Export scGCL results to Seurat-compatible format.

    Creates files that can be loaded into R/Seurat:
    - counts.csv: Expression matrix
    - metadata.csv: Cell metadata with clusters
    - embeddings.csv: scGCL embeddings
    - load_seurat.R: R script to load the data

    Parameters
    ----------
    X : np.ndarray
        Expression matrix (cells x genes)
    labels : np.ndarray
        Cluster labels
    embeddings : np.ndarray
        Cell embeddings
    confidence : np.ndarray, optional
        Confidence scores
    gene_names : list, optional
        Gene names
    cell_names : list, optional
        Cell names
    output_dir : str
        Output directory
    project_name : str
        Project name for Seurat object

    Returns
    -------
    str
        Path to output directory
    """
    os.makedirs(output_dir, exist_ok=True)

    n_cells, n_genes = X.shape

    if gene_names is None:
        gene_names = [f"Gene_{i}" for i in range(n_genes)]
    if cell_names is None:
        cell_names = [f"Cell_{i}" for i in range(n_cells)]

    # Save expression matrix (transposed for Seurat: genes x cells)
    counts_df = pd.DataFrame(X.T, index=gene_names, columns=cell_names)
    counts_path = os.path.join(output_dir, "counts.csv")
    counts_df.to_csv(counts_path)

    # Save metadata
    metadata = pd.DataFrame({
        'scgcl_clusters': labels,
    }, index=cell_names)

    if confidence is not None:
        metadata['scgcl_confidence'] = confidence

    metadata_path = os.path.join(output_dir, "metadata.csv")
    metadata.to_csv(metadata_path)

    # Save embeddings
    emb_df = pd.DataFrame(
        embeddings,
        index=cell_names,
        columns=[f"scGCL_{i+1}" for i in range(embeddings.shape[1])]
    )
    emb_path = os.path.join(output_dir, "embeddings.csv")
    emb_df.to_csv(emb_path)

    # Generate R script
    r_script = f'''# Load scGCL results into Seurat
# Generated by scGCL

library(Seurat)

# Load expression matrix
counts <- read.csv("counts.csv", row.names = 1)
counts <- as.matrix(counts)

# Create Seurat object
seurat_obj <- CreateSeuratObject(
  counts = counts,
  project = "{project_name}",
  min.cells = 0,
  min.features = 0
)

# Load metadata
metadata <- read.csv("metadata.csv", row.names = 1)
seurat_obj <- AddMetaData(seurat_obj, metadata)

# Load embeddings
embeddings <- read.csv("embeddings.csv", row.names = 1)
embeddings <- as.matrix(embeddings)

# Add embeddings as a dimensional reduction
seurat_obj[["scgcl"]] <- CreateDimReducObject(
  embeddings = embeddings,
  key = "scGCL_",
  assay = "RNA"
)

# Set cluster identity
Idents(seurat_obj) <- "scgcl_clusters"

# Run UMAP on scGCL embeddings
seurat_obj <- RunUMAP(seurat_obj, reduction = "scgcl", dims = 1:ncol(embeddings))

# Visualize
DimPlot(seurat_obj, reduction = "umap", group.by = "scgcl_clusters")

# Save object
saveRDS(seurat_obj, "seurat_object.rds")

cat("Seurat object saved to seurat_object.rds\\n")
'''

    r_script_path = os.path.join(output_dir, "load_seurat.R")
    with open(r_script_path, 'w') as f:
        f.write(r_script)

    print(f"Seurat export saved to {output_dir}/")
    print(f"  - counts.csv: Expression matrix ({n_genes} genes x {n_cells} cells)")
    print(f"  - metadata.csv: Cell metadata with clusters")
    print(f"  - embeddings.csv: scGCL embeddings")
    print(f"  - load_seurat.R: R script to load into Seurat")

    return output_dir


def to_cellxgene(
    adata,
    output_path: str = "cellxgene.h5ad",
    title: str = "scGCL Analysis"
) -> str:
    """
    Export AnnData to cellxgene-compatible format.

    Parameters
    ----------
    adata : AnnData
        Annotated data object with scGCL results
    output_path : str
        Output H5AD file path
    title : str
        Dataset title

    Returns
    -------
    str
        Path to output file
    """
    import anndata

    # Make a copy
    adata_export = adata.copy()

    # Ensure required fields for cellxgene
    if 'scgcl_clusters' in adata_export.obs:
        adata_export.obs['scgcl_clusters'] = adata_export.obs['scgcl_clusters'].astype('category')

    # Add schema info
    adata_export.uns['title'] = title
    adata_export.uns['schema_version'] = '3.0.0'

    # Ensure X is dense for compatibility
    if hasattr(adata_export.X, 'toarray'):
        adata_export.X = adata_export.X.toarray()

    adata_export.write_h5ad(output_path)
    print(f"Saved cellxgene-compatible file to {output_path}")

    return output_path


def to_loom(
    X: np.ndarray,
    labels: np.ndarray,
    embeddings: np.ndarray,
    gene_names: Optional[List[str]] = None,
    cell_names: Optional[List[str]] = None,
    output_path: str = "scgcl.loom"
) -> str:
    """
    Export to Loom format for use with SCENIC, etc.

    Parameters
    ----------
    X : np.ndarray
        Expression matrix
    labels : np.ndarray
        Cluster labels
    embeddings : np.ndarray
        Cell embeddings
    gene_names : list, optional
        Gene names
    cell_names : list, optional
        Cell names
    output_path : str
        Output file path

    Returns
    -------
    str
        Path to output file
    """
    try:
        import loompy
    except ImportError:
        raise ImportError("loompy required for Loom export. Install with: pip install loompy")

    n_cells, n_genes = X.shape

    if gene_names is None:
        gene_names = [f"Gene_{i}" for i in range(n_genes)]
    if cell_names is None:
        cell_names = [f"Cell_{i}" for i in range(n_cells)]

    # Row attributes (genes)
    row_attrs = {
        "Gene": np.array(gene_names)
    }

    # Column attributes (cells)
    col_attrs = {
        "CellID": np.array(cell_names),
        "scgcl_clusters": labels.astype(int),
    }

    # Add embedding dimensions
    for i in range(embeddings.shape[1]):
        col_attrs[f"scGCL_{i+1}"] = embeddings[:, i]

    # Create loom file (genes x cells)
    loompy.create(output_path, X.T, row_attrs, col_attrs)
    print(f"Saved Loom file to {output_path}")

    return output_path


def export_markers_to_gmt(
    markers_df: pd.DataFrame,
    output_path: str = "markers.gmt",
    description: str = "scGCL marker genes"
) -> str:
    """
    Export marker genes to GMT format for GSEA.

    Parameters
    ----------
    markers_df : pd.DataFrame
        Marker genes DataFrame with 'cluster' and 'gene' columns
    output_path : str
        Output GMT file path
    description : str
        Gene set description

    Returns
    -------
    str
        Path to output file
    """
    with open(output_path, 'w') as f:
        for cluster in sorted(markers_df['cluster'].unique()):
            genes = markers_df[markers_df['cluster'] == cluster]['gene'].tolist()
            gene_str = '\t'.join(genes)
            f.write(f"Cluster_{cluster}\t{description}\t{gene_str}\n")

    print(f"Saved GMT file to {output_path}")
    return output_path
